markdown: rdiscount
permalink: /:title/
url: http://hehehe.xyz
name: 呵呵呵
author: Thau
qq: 
email: thau@qq.com
duoshuo: Dacaitou
beian:
cnzz: 119959
weibo: Dacaitou
github: Bigcaitou
pygments: true
safe: true
paginate: 20
about: "hehehe"
